### ISSUE TITLE
Can't push my local commit

### ISSUE THREAD

**Issue by chanijjani** [hokeun/lf-rust-rti#1]
Dear @hokeun , please check my push permission in this repo :)

**Comment by hokeun** [comment]
Dear @chanijjani , I think you should already have the write access as a collaborator (https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-user-account-settings/permission-levels-for-a-personal-account-repository#collaborator-access-for-a-repository-owned-by-a-personal-account)

Could you provide the error messages you got?

**Comment by chanijjani** [comment]
remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/hokeun/lf-rust-rti.git/'

**Comment by chanijjani** [comment]
I solved this problem with the ssh URL. Thanks!
