### ISSUE TITLE
Add Integration tests

### ISSUE THREAD

**Issue by chanijjani** [hokeun/lf-rust-rti#25]
Test the public interfaces of our modules with any other external modules.

**Comment by hokeun** [comment]
yml file for CI tests in LF repoo: https://github.com/lf-lang/reactor-c/blob/main/.github/workflows/ci.yml
Example run of CI tests: [lf-default / regular-tests (ubuntu-latest)](https://github.com/lf-lang/reactor-c/actions/runs/7747248876/job/21127276520#logs)

**Comment by chanijjani** [comment]
Rust RTI replacement test with an integration test case (HelloDistributed) in Lingua Franca (LF)
[LF_integration_test-HelloDistributed_with_rust_rti.txt](https://github.com/hokeun/lf-rust-rti/files/14187712/LF_integration_test-HelloDistributed_with_rust_rti.txt)

**Comment by chanijjani** [comment]
https://github.com/chanijjani/lingua-franca/pull/1
